[package]
name = "techsihir-newsletter"
version = "0.1.0"
authors = ["Abdulbasit (techsihir) <abdulbasit@techsihir.com> "]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "techsihir-newsletter"

[dependencies]
actix-web = "4.14.1"
reqwest = "0.13.4"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
serde = { features = ["derive"], version = "1.0.229" }


[dependencies.sqlx]
version = "~0.8"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
]
